### ISSUE TITLE
No content shown in the calendar

### ISSUE THREAD

**Issue by kelvinau** [lkmadushan/vue-tuicalendar#2]
I followed almost exactly from your example, but there's nothing shown except the header (and you are missing the '=>' in `this.$refs.calendar.registerEvent("beforeDeleteSchedule", event {`).

![2018-07-12 08_44_18-schedule vue - school-course - visual studio code](https://user-images.githubusercontent.com/5885902/42644162-bb7afd2a-85af-11e8-8946-507e5fb02142.png)

![2018-07-12 08_39_42- schedule vue - school-course - visual studio code](https://user-images.githubusercontent.com/5885902/42643886-13aeb1f4-85af-11e8-9233-485ca1da33a8.png)

This is the tui calendar option I coped directly from their official website.

![2018-07-12 08_43_25-schedule vue - school-course - visual studio code](https://user-images.githubusercontent.com/5885902/42644107-9866d7d2-85af-11e8-8463-04004309f985.png)

Result
![2018-07-12 08_45_58-schedule - 1000 class _ california community college online course](https://user-images.githubusercontent.com/5885902/42644251-f911bd5e-85af-11e8-9f62-70684c98547f.png)

**Comment by lkmadushan** [comment]
@kelvinau it's working for me.

https://codesandbox.io/s/mox6wwp609

Can you share a code sandbox example?

**Comment by lkmadushan** [comment]
there was an issues in month view, it's already fixed

@kelvinau https://github.com/nhnent/tui.calendar/issues/161
