### ISSUE TITLE
Why is there a google analytics ping in this package?

### ISSUE THREAD

**Issue by HIMISOCOOL** [lkmadushan/vue-tuicalendar#3]
I see no references to analytics in the actual source here on GitHub but when I am using it I get this
![image](https://user-images.githubusercontent.com/1725300/43171704-716caefe-8fff-11e8-95f1-8ea109ed3f32.png)

![image](https://user-images.githubusercontent.com/1725300/43171619-21928034-8fff-11e8-8205-63401f17f10e.png)
It's a bit shady.

**Comment by lkmadushan** [comment]
@HIMISOCOOL This is just a wrapper around tui-calendar. Can you ask this question on their thread.
