### ISSUE TITLE
Weird rendering issue

### ISSUE THREAD

**Issue by mihailtd** [lkmadushan/vue-tuicalendar#4]
Hello,
I have some rendering problems and I don't know how to solve them because `this.$refs.calendar.fireMethod('render')` doesn't do the trick.
Basically the month view does not render while the others work fine on the initial load.
Also when I use `next` or prev methods on any view it stops rendering, but if i change the view to something else then back it works again:
![2018-09-06_23-50-35](https://user-images.githubusercontent.com/7993468/45184480-af5b3f80-b22f-11e8-876e-2142f3cf492f.gif)

Any ideeas?

Thank you!

**Comment by lkmadushan** [comment]
@farcasmihai91 can you provide an example?
